apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ $.Chart.Name }}-{{ .Values.namespace }}-volume"
spec:
  capacity:
    storage: "{{ .Values.persistentVolume.capacity.storage }}"
  volumeMode: "{{ .Values.persistentVolume.volumeMode }}"
  accessModes: 
  - "{{ .Values.persistentVolume.accessModes}}"
  storageClassName: "{{ .Values.persistentVolume.storageClassName}}"
  local: 
    path: "{{ .Values.persistentVolume.path }}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "{{ .Values.nodeSelector.key }}"
          operator: In
          values:
          - "{{ .Values.nodeSelector.value }}"