pipeline {
    agent any

    stages {
        stage('STAGING') {
            environment {
                CONFIG = credentials('kubeconfig')
                ENV    = 'staging'
            }

            steps {
                sh 'bash scripts/undeploy_helm.sh'
            }
        }
        
        stage('PRE-PROD') {
            environment {
                CONFIG = credentials('kubeconfig')
                ENV    = 'pre-prod'
            }

            steps {
                sh 'bash scripts/undeploy_helm.sh'
            }
        }
        
        stage('PRODUCTION') {
            environment {
                CONFIG = credentials('kubeconfig')
                ENV    = 'production'
            }

            steps {
                sh 'bash scripts/undeploy_helm.sh'
            }
        }
    }
}