def createNamespace (namespace) {
    echo "Creating namespace ${namespace} if needed"

    sh "[ ! -z \"\$(kubectl get ns ${namespace} -o name 2>/dev/null)\" ] || kubectl create ns ${namespace}"
}

pipeline {
    agent any

    stages {
        stage('STAGING') {
            environment {
                    CONFIG = credentials('kubeconfig')
                    ENV    = 'staging'
            }

            steps {
                script {
                    createNamespace(${ENV})
                }
                sh 'bash scripts/pre-checks.sh'
                sh 'bash scripts/deploy_helm.sh'
                sh 'bash scripts/post-checks.sh'
            }
        }
        
        stage('PRE-PROD') {
            environment {
                    CONFIG = credentials('kubeconfig')
                    ENV    = 'pre-prod'
            }

            steps {
                script {
                    createNamespace(${ENV})
                }
                sh 'bash scripts/pre-checks.sh'
                sh 'bash scripts/deploy_helm.sh'
                sh 'bash scripts/post-checks.sh'
            }
        }
        
        
        stage('PRODUCTION') {
            environment {
                    CONFIG = credentials('kubeconfig')
                    ENV    = 'production'
            }

            steps {
                script {
                    createNamespace(${ENV})
                }
                sh 'bash scripts/pre-checks.sh'
                sh 'bash scripts/deploy_helm.sh'
                sh 'bash scripts/post-checks.sh'
            }
        }
    }
}