pipeline {
    agent any

    stages {
        stage('STAGING') {
            environment {
                    CONFIG = credentials('kubeconfig')
                    ENV    = 'staging'
            }

            steps {
                sh 'bash scripts/pre-checks.sh'
                sh 'bash scripts/deploy_helm.sh'
                sh 'bash scripts/post-checks.sh'
            }
        }
        
        stage('PRE-PROD') {
            environment {
                    CONFIG = credentials('kubeconfig')
                    ENV    = 'pre-prod'
            }

            steps {
                sh 'bash scripts/pre-checks.sh'
                sh 'bash scripts/deploy_helm.sh'
                sh 'bash scripts/post-checks.sh'
            }
        }
        
        
        stage('PRODUCTION') {
            environment {
                    CONFIG = credentials('kubeconfig')
                    ENV    = 'production'
            }

            steps {
                sh 'bash scripts/pre-checks.sh'
                sh 'bash scripts/deploy_helm.sh'
                sh 'bash scripts/post-checks.sh'
            }
        }
    }
}