apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ $.Chart.Name }}-autoscaler"
  namespace: "{{ .Values.namespace }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ $.Chart.Name }}-deployment"
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics: 
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization 
        averageValue: {{ .Values.autoscaling.targetMemoryUtilization }}