apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ $.Chart.Name }}-pdb"
  namespace: "{{ .Values.namespace }}"
spec:
  maxUnavailable: {{ .Values.poddisruptionbudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}