apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $.Chart.Name }}-volume-claim"
  namespace: "{{ .Values.namespace }}"
spec:
  storageClassName: "{{ .Values.persistentVolume.storageClassName}}"
  accessModes:
    - "{{ .Values.persistentVolume.accessModes}}"
  resources:
    requests:
      storage: "{{ .Values.persistentVolume.capacity.storage }}"